In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("derrickmwiti/google-2019-cluster-sample")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/derrickmwiti/google-2019-cluster-sample?dataset_version_number=1...

100%|██████████| 96.7M/96.7M [00:01<00:00, 63.2MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/derrickmwiti/google-2019-cluster-sample/versions/1

In [ ]:
import pandas as pd

df  = pd.read_csv("/root/.cache/kagglehub/datasets/derrickmwiti/google-2019-cluster-sample/versions/1/borg_traces_data.csv")
df.head()

,Unnamed: 0,time,instance_events_type,collection_id,scheduling_class,collection_type,priority,alloc_collection_id,instance_index,machine_id,...,assigned_memory,page_cache_memory,cycles_per_instruction,memory_accesses_per_instruction,sample_rate,cpu_usage_distribution,tail_cpu_usage_distribution,cluster,event,failed
0,0,0,2,94591244395,3,1,200,0,144,168846390496,...,0.014435,0.000415,NaN,NaN,1.0,[0.00314331 0.00381088 0.00401306 0.00415039 0...,[0.00535583 0.00541687 0.00548553 0.00554657 0...,7,FAIL,1
1,1,2517305308183,2,260697606809,2,0,360,221495397286,335,85515092,...,0.000000,0.000000,NaN,NaN,1.0,[1.23977661e-05 1.23977661e-05 1.23977661e-05 ...,[1.23977661e-05 1.23977661e-05 1.23977661e-05 ...,7,FAIL,1
2,2,195684022913,6,276227177776,2,0,103,0,376,169321752432,...,0.010422,0.000235,0.939919,0.001318,1.0,[0.01344299 0.01809692 0.0201416 0.02246094 0...,[0.02902222 0.02929688 0.0295105 0.0296936 0...,7,SCHEDULE,0
3,3,0,2,10507389885,3,0,200,0,1977,178294817221,...,0.041626,0.000225,1.359102,0.007643,1.0,[0.03704834 0.04125977 0.04290771 0.04425049 0...,[0.05535889 0.05584717 0.05633545 0.05718994 0...,8,FAIL,1
4,4,1810627494172,3,25911621841,2,0,0,0,3907,231364893292,...,0.000272,0.000010,NaN,NaN,1.0,[0. 0. 0. 0. 0...,[0.00041485 0.00041485 0.00041485 0.00041485 0...,2,FINISH,0

In [ ]:
df.columns

Index(['Unnamed: 0', 'time', 'instance_events_type', 'collection_id',
       'scheduling_class', 'collection_type', 'priority',
       'alloc_collection_id', 'instance_index', 'machine_id',
       'resource_request', 'constraint', 'collections_events_type', 'user',
       'collection_name', 'collection_logical_name',
       'start_after_collection_ids', 'vertical_scaling', 'scheduler',
       'start_time', 'end_time', 'average_usage', 'maximum_usage',
       'random_sample_usage', 'assigned_memory', 'page_cache_memory',
       'cycles_per_instruction', 'memory_accesses_per_instruction',
       'sample_rate', 'cpu_usage_distribution', 'tail_cpu_usage_distribution',
       'cluster', 'event', 'failed'],
      dtype='object')

In [ ]:
df = df[['start_time', 'end_time', 'average_usage', 'maximum_usage','cpu_usage_distribution','cluster']]

In [ ]:
df= df.sort_values(by = ["cluster","start_time"])
df.drop_duplicates(subset="start_time",keep="first", inplace=True)
df.shape
df

,start_time,end_time,average_usage,maximum_usage,cpu_usage_distribution,cluster
124124,9000000000,9300000000,"{'cpus': 0.0001049041748046875, 'memory': 0.00...","{'cpus': 0.0005035400390625, 'memory': 0.00155...",[7.91549683e-05 8.29696655e-05 8.77380371e-05 ...,1
1493,17100000000,17400000000,"{'cpus': 0.0084686279296875, 'memory': 0.00604...","{'cpus': 0.028228759765625, 'memory': 0.007041...",[0.00236893 0.00757599 0.00785828 0.00799561 0...,1
113179,21000000000,21300000000,"{'cpus': 0.0002880096435546875, 'memory': 0.03...","{'cpus': 0.006927490234375, 'memory': 0.038452...",[0.00012493 0.00013924 0.00014782 0.0001564 0...,1
2760,26100000000,26400000000,"{'cpus': 0.00492095947265625, 'memory': 0.0065...","{'cpus': 0.0213623046875, 'memory': 0.00757598...",[0.00021839 0.00270844 0.00350952 0.00409698 0...,1
1519,38400000000,38700000000,"{'cpus': 0.005401611328125, 'memory': 0.004814...","{'cpus': 0.0263671875, 'memory': 0.00572967529...",[0.00019932 0.00026989 0.00432587 0.00531769 0...,1
...,...,...,...,...,...,...
29845,2661300000000,2661600000000,"{'cpus': 0.002368927001953125, 'memory': 0.005...","{'cpus': 0.00749969482421875, 'memory': 0.0060...",[0.0020256 0.00215149 0.00220108 0.0022316 0...,8
86107,2665800000000,2666100000000,"{'cpus': 0.0150146484375, 'memory': 0.00495147...","{'cpus': 0.069091796875, 'memory': 0.005928039...",[0.00087833 0.00886536 0.00891113 0.00895691 0...,8
1565,2669100000000,2669400000000,"{'cpus': 0.003582000732421875, 'memory': 0.000...","{'cpus': 0.008056640625, 'memory': 0.000701904...",[0.00231171 0.00270844 0.00292206 0.00309753 0...,8
21989,2670600000000,2670900000000,"{'cpus': 0.010711669921875, 'memory': 0.001659...","{'cpus': 0.0198974609375, 'memory': 0.00195693...",[0.00016594 0.00773621 0.00871277 0.01118469 0...,8
203815,2677510000000,2677513000000,"{'cpus': 0.00012493133544921875, 'memory': 8.7...","{'cpus': 0.000324249267578125, 'memory': 8.869...",[0. 0. 0. 0. 0...,8